

PROC IMPORT
    DATAFILE= "//ad.ucsd.edu/AHS/PSYC/KREMEN/Tyler/ACTIVE Long C Felix 06012023.sav"
    OUT=ACTIVE4
    DBMS=SPSS;
RUN;
title;


ODS PDF FILE = 'C:/Users/tyler/Downloads/output-file-name.pdf';


PROC MIXED DATA=ACTIVE4 NOCLPRINT NOITPRINT;
WHERE INTGRP = 1 OR INTGRP  = 4;
 CLASS ID RACE FEMALE;
MODEL ZMEMCB =    DEP_9_BIN_B
DEP_9_BIN_WP|INTGRP_MEM|VISIT
YRSEDUC RACE FEMALE BASEAGE BASEMMSE / SOLUTION;
REPEATED /SUBJECT = ID TYPE = UN;
 ESTIMATE 'Interaction Effect at Visit 2'
    DEP_9_BIN_WP*INTGRP_MEM*VISIT 6 / df = 2748 cl;
 ESTIMATE 'Interaction Effect at Visit 3'
    DEP_9_BIN_WP*INTGRP_MEM*VISIT 52 / df = 2057;
 ESTIMATE 'Interaction Effect at Visit 4'
    DEP_9_BIN_WP*INTGRP_MEM*VISIT 104 / df = 1949;
 ESTIMATE 'Interaction Effect at Visit 5'
    DEP_9_BIN_WP*INTGRP_MEM*VISIT 156 / df = 1820;
 ESTIMATE 'Interaction Effect at Visit 6'
    DEP_9_BIN_WP*INTGRP_MEM*VISIT 260 / df = 1546;
 ESTIMATE 'Interaction Effect at Visit 7'
    DEP_9_BIN_WP*INTGRP_MEM*VISIT 520 / df = 897;
RUN;



PROC MIXED DATA=ACTIVE4 NOCLPRINT NOITPRINT;
WHERE INTGRP = 2 OR INTGRP  = 4;
 CLASS ID RACE FEMALE;
MODEL ZREASCB =    DEP_9_BIN_B
DEP_9_BIN_WP|INTGRP_REAS|VISIT
YRSEDUC RACE FEMALE BASEAGE BASEMMSE / SOLUTION;
REPEATED /SUBJECT = ID TYPE = UN;
 ESTIMATE 'Interaction Effect at Visit 2'
    DEP_9_BIN_WP*INTGRP_REAS*VISIT 6 / df = 2748 cl;
 ESTIMATE 'Interaction Effect at Visit 3'
    DEP_9_BIN_WP*INTGRP_REAS*VISIT 52 / df = 2057;
 ESTIMATE 'Interaction Effect at Visit 4'
    DEP_9_BIN_WP*INTGRP_REAS*VISIT 104 / df = 1949;
 ESTIMATE 'Interaction Effect at Visit 5'
    DEP_9_BIN_WP*INTGRP_REAS*VISIT 156 / df = 1820;
 ESTIMATE 'Interaction Effect at Visit 6'
    DEP_9_BIN_WP*INTGRP_REAS*VISIT 260 / df = 1546;
 ESTIMATE 'Interaction Effect at Visit 7'
    DEP_9_BIN_WP*INTGRP_REAS*VISIT 520 / df = 897;
RUN;



PROC MIXED DATA=ACTIVE4 NOCLPRINT NOITPRINT;
WHERE INTGRP = 3 OR INTGRP  = 4;
 CLASS ID RACE FEMALE;
MODEL ZSPDCB =    DEP_9_BIN_B
DEP_9_BIN_WP|INTGRP_SPD|VISIT
YRSEDUC RACE FEMALE BASEAGE BASEMMSE / SOLUTION;
REPEATED /SUBJECT = ID TYPE = UN;
 ESTIMATE 'Interaction Effect at Visit 2'
    DEP_9_BIN_WP*INTGRP_SPD*VISIT 6 / df = 2748 cl;
 ESTIMATE 'Interaction Effect at Visit 3'
    DEP_9_BIN_WP*INTGRP_SPD*VISIT 52 / df = 2057;
 ESTIMATE 'Interaction Effect at Visit 4'
    DEP_9_BIN_WP*INTGRP_SPD*VISIT 104 / df = 1949;
 ESTIMATE 'Interaction Effect at Visit 5'
    DEP_9_BIN_WP*INTGRP_SPD*VISIT 156 / df = 1820;
 ESTIMATE 'Interaction Effect at Visit 6'
    DEP_9_BIN_WP*INTGRP_SPD*VISIT 260 / df = 1546;
 ESTIMATE 'Interaction Effect at Visit 7'
    DEP_9_BIN_WP*INTGRP_SPD*VISIT 520 / df = 897;
RUN;

ods pdf close;


DATA ACTIVE4;
SET ACTIVE4;
ALLGROUP = .;
IF INTGRP = 1 AND DEP_9_BIN_WP = 1 THEN ALLGROUP = 1;
IF INTGRP = 1 AND DEP_9_BIN_WP = 0 THEN ALLGROUP = 2;
IF INTGRP = 2 AND DEP_9_BIN_WP = 1 THEN ALLGROUP = 3;
IF INTGRP = 2 AND DEP_9_BIN_WP = 0 THEN ALLGROUP = 4;
IF INTGRP = 3 AND DEP_9_BIN_WP = 1 THEN ALLGROUP = 5;
IF INTGRP = 3 AND DEP_9_BIN_WP = 0 THEN ALLGROUP = 6;
IF INTGRP = 4 AND DEP_9_BIN_WP = 1 THEN ALLGROUP = 7;
IF INTGRP = 4 AND DEP_9_BIN_WP = 0 THEN ALLGROUP = 8;
RUN;

 proc format ;
  value tmp
    1="Memory - Dep"
    2="Memory - No Dep"
    3 = "Reas - Dep"
    4 = "Reas - No Dep"
    5 = "Speed - Dep"
    6 = "Speed - No Dep"
    7 = "Control - Dep"
    8 = "Control - No Dep";
run;


data ACTIVE4;
  set ACTIVE4;
  format ALLGROUP tmp.;
run;


 PROC SGPLOT DATA=ACTIVE4;
  WHERE (INTGRP= 1 OR INTGRP = 4);
   VLINE VISIT_RC/ RESPONSE=MEMCB_WP GROUP=ALLGROUP STAT=MEAN LIMITSTAT=STDERR;
   YAXIS LABEL='MEAN +/- SEM';
   STYLEATTRS DATACONTRASTCOLORS=(RED BLUE ORANGE BLACK)
      DATASYMBOLS=(CIRCLEFILLED TRIANGLEFILLED SQUAREFILLED DOT)
      DATALINEPATTERNS=(SOLID DASH LONGDASH DOT);
RUN;


 PROC SGPLOT DATA=ACTIVE4;
  WHERE (INTGRP= 1 OR INTGRP = 4);
   VLINE VISIT_RC/ RESPONSE=MEMCB_WP GROUP=ALLGROUP STAT=MEAN LIMITSTAT=STDERR;
   YAXIS LABEL='MEAN +/- SEM';
   STYLEATTRS DATACONTRASTCOLORS=(RED BLUE ORANGE BLACK)
      DATASYMBOLS=(CIRCLEFILLED TRIANGLEFILLED SQUAREFILLED DOT)
      DATALINEPATTERNS=(SOLID DASH LONGDASH DOT);
RUN;

 PROC SGPLOT DATA=ACTIVE4;
  WHERE (INTGRP= 1 OR INTGRP = 4);
   VLINE VISIT_RC/ RESPONSE=MEMCB_WP GROUP=ALLGROUP STAT=MEAN LIMITSTAT=STDERR;
   YAXIS LABEL='MEAN +/- SEM';
   STYLEATTRS DATACONTRASTCOLORS=(RED BLUE ORANGE BLACK)
      DATASYMBOLS=(CIRCLEFILLED TRIANGLEFILLED SQUAREFILLED DOT)
      DATALINEPATTERNS=(SOLID DASH LONGDASH DOT);
RUN;





*DATA CHECKING AND RE-CODING;


PROC MEANS DATA=ACTIVE4;
VAR MEMCB REASCB SPDCB;
RUN;

DATA ACTIVE4;
SET ACTIVE4;
ZMEMCB = MEMCB/2.38;
ZREASCB = REASCB/2.67;
ZSPDCB = SPDCB/2.46;
RUN;

PROC FREQ DATA = ACTIVE4;
TABLE VISIT;
RUN;


*DATA ACTIVE4;
*SET ACTIVE4;
IF VISIT = 1 THEN VISIT = 0;
*IF VISIT = 2 THEN VISIT = 6;
*IF VISIT = 3 THEN VISIT = 52;
*IF VISIT = 4 THEN VISIT = 104;
*IF VISIT = 5 THEN VISIT = 156;
*IF VISIT = 6 THEN VISIT = 260;
*IF VISIT = 7 THEN VISIT = 520;
*RUN;

DATA ACTIVE4;
SET ACTIVE4;
IF VISIT = 0  THEN VISIT_RC = 1;
IF VISIT = 6  THEN VISIT_RC = 2;
IF VISIT = 52  THEN VISIT_RC = 3;
IF VISIT = 104  THEN VISIT_RC = 4;
IF VISIT = 156  THEN VISIT_RC = 5;
IF VISIT = 260  THEN VISIT_RC = 6;
IF VISIT = 520  THEN VISIT_RC = 7;
RUN;

DATA ACTIVE4;
SET ACTIVE4;
INTGRP_MEM = .;
INTGRP_REAS = .;
INTGRP_SPD = .;
IF INTGRP = 1 THEN INTGRP_MEM = 1;
IF INTGRP = 4 THEN INTGRP_MEM = 0;
IF DEP_9_BIN_WP = - 1 THEN DEP_9_BIN_WP = 0;
IF INTGRP = 2 THEN INTGRP_REAS = 1;
IF INTGRP = 4 THEN INTGRP_REAS = 0;
IF INTGRP = 3 THEN INTGRP_SPD = 1;
IF INTGRP = 4 THEN INTGRP_SPD = 0;
RUN;



